version: '3.8'

services:
  # DNS (Bind9)
  dns:
    build: 
      context: ./dns
      dockerfile: Dockerfile
    image: dns
    container_name: dns
    networks:
      - miami-networks
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - ./dns/zones/db.miami.asa.br:/etc/bind/db.miami.asa.br
      - ./dns/named.conf.local:/etc/bind/named.conf.local

  # Proxy Reverso (NGINX com HTTPS)
  proxy:
    build: 
      context: ./proxy
      dockerfile: Dockerfile
    image: proxy
    container_name: proxy
    ports:
      - "80:80"
      - "443:443"
    networks:
      - miami-networks
    depends_on:
      - dns
      - email
      - webmail
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy/ssl:/etc/nginx/ssl

  # Servidor de E-mail (Postfix + Dovecot)
  email:
    build: 
      context: ./email
      dockerfile: Dockerfile
    image: email
    container_name: email
    networks:
      - miami-networks
    ports:
      - "25:25/tcp"
      - "587:587/tcp"
      - "110:110/tcp"
      - "143:143/tcp"
      - "465:465/tcp"
    volumes:
      - ./email/postifix-dovecot/main.cf:/etc/postfix/main.cf
      - ./email/postifix-dovecot/dovecot.conf:/etc/dovecot/dovecot.conf
      - ./email/postifix-dovecot/10-master.conf:/etc/dovecot/conf.d/10-master.conf
      - ./email/data:/home

  # Webmail (Roundcube)
  webmail:
    image: roundcube/roundcubemail:latest
    container_name: webmail
    networks:
      - miami-networks
    environment:
      - ROUNDCUBEMAIL_DEFAULT_HOST=tls://email:143
      - ROUNDCUBEMAIL_SMTP_SERVER=tls://email:25
      - ROUNDCUBEMAIL_DB_TYPE=sqlite
    depends_on:
      - email
    volumes:
      - ./webmail/conf/config.inc.php:/var/roundcube/config/config.inc.php

  # Servidor SSH
  ssh:
    image: ubuntu:latest
    container_name: ssh
    command: |
      bash -c "apt update && 
      apt install -y openssh-server && 
      echo 'PermitRootLogin no' >> /etc/ssh/sshd_config && 
      service ssh start && 
      tail -f /dev/null"
    networks:
      - miami-networks
    ports:
      - "22:22"

networks:
  miami-networks:
    driver: bridge

volumes:
  maildata: