version: '3.8'

services:
  # DNS (Bind9)
  dns:
    build: ./dns
    container_name: dns
    networks:
      - asa-networks
    ports:
      - "53:53/udp"
    volumes:
      - ./dns/zones:/etc/bind/zones

  # Proxy Reverso (NGINX com HTTPS)
  proxy:
    build: ./proxy
    container_name: proxy
    ports:
      - "80:80"
      - "443:443"
    networks:
      - asa-networks
    depends_on:
      - webmail
    volumes:
      - ./proxy/ssl:/etc/nginx/ssl

  # Servidor de E-mail (Postfix + Dovecot)
  email:
    build: ./email
    container_name: email
    networks:
      - asa-networks
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
    volumes:
      - maildata:/var/mail

  # Webmail (Roundcube)
  webmail:
    image: roundcube/roundcubemail:latest
    container_name: webmail
    networks:
      - asa-networks
    environment:
      - ROUNDCUBEMAIL_DEFAULT_HOST=email
    depends_on:
      - email

  # Servidor SSH
  ssh:
    image: ubuntu:latest
    container_name: ssh
    command: |
      bash -c "apt update && 
      apt install -y openssh-server && 
      echo 'PermitRootLogin no' >> /etc/ssh/sshd_config && 
      service ssh start && 
      tail -f /dev/null"
    networks:
      - asa-networks
    ports:
      - "22:22"

networks:
  asa-networks:
    driver: bridge

volumes:
  maildata: